nodeLinker: node-modules

# Suppress peer dependency warning: @auth/mongodb-adapter declares mongodb@^6 but we use mongodb@7 (compatible)
logFilters:
  - pattern: "*@auth/mongodb-adapter*mongodb*"
    level: discard
  - pattern: "*@auth/mongodb-adapter*peer*"
    level: discard
